### ISSUE TITLE
using FindDiff 

### ISSUE THREAD

**Issue by Emlyn25** [jasleenkapoor/Python-Project-#14]
First import:

from findiff import FinDiff

Then when using incode: e.g.

H = -0.5 * FinDiff(0, dx, 2).matrix(x_array.shape) + v_x_matrix

**Comment by ZHAP054** [comment]
Do you remember what we typed into the command line to import the findiff package? I never imported it to my branch.

**Comment by ZHAP054** [comment]
I know, you have to type "pip install findiff" into your anaconda PowerShell command line

**Comment by zhap066** [comment]
**Case**
Question raised (by Jamie) about the use of FinDiff. Emlyn offered import advice. Jamie used the prompt command to install findiff. Problem resolved. Discussion between myself and Jamie on the issue and the successful resolution 

**Parties**
Jamie, Emlyn, Jessica

**Closed**
16:37 
11/11/2022
