### ISSUE TITLE
Assign roles

### ISSUE THREAD

**Issue by zhap066** [jasleenkapoor/Python-Project-#6]
DETERMINED AVALABLE ROLES

**Coding (defining a data set, defining functions, plotting, testing - animation)**
- Emlyn
- Jamie
- Matthew

**Git Consultant**
- Jessica

**User Interface Coding**
- Alex

**Documentation (Doc Strings)**
- Jasleen

**Software Package**
- Alex
- Jessica

**Code review**
- Matthew

**Comment by MattWebb01** [comment]
Sounds good to me.
